[package]
name = "chksm_rs"
version = "0.1.0"
authors = ["aebur"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8.0"
structopt = "0.3.1"