name: Rust

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test Major Platforms
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose

  create_release:
    runs-on: [ubuntu-latest]
    needs: [test]
    steps:
      - name: Create GH Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build_ubuntu:
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Ubuntu
        run: cargo build --quiet --release
      - name: Upload Ubuntu Asset
        id: upload-ubuntu-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.create_release.outputs.upload_url }}
          asset_path: target/release/chksm
          asset_name: chksm-ubuntu-latest
        
  
  build_windows:
    needs: [test, build_ubuntu]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Windows
        run: cargo build --quiet --release
      - name: Upload Windows Asset
        id: upload-windows-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.create_release.outputs.upload_url }}
          asset_path: target/release/chksm.exe
          asset_name: chksm-windows-latest.exe

  build_macos:
    needs: [test, build_ubuntu]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build macOS
        run: cargo build --quiet --release
      - name: Upload macOS Asset
        id: upload-macos-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.create_release.outputs.upload_url }}
          asset_path: target/release/chksm
          asset_name: chksm-macos-latest
