name: Rust

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
  
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        asset_files: [chksm_rs.exe, chksm_rs]
    name: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_token: ${{ steps.create-release.outputs.upload_url }}
        asset_path: target/release/${{ matrix.asset_files }}
        asset_name: ${{ matrix.asset_files }}
